name: Publish

on:
  release:
    types: [created]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Get version
      run: |
        WQP_VERSION=$(python -c "import wqp; print(wqp.__version__)")
        echo export WQP_VERSION=$WQP_VERSION >> $BASH_ENV
        echo Delivering version $WQP_VERSION...

    - name: Build Package
      run: |
        python setup.py sdist
        echo export TAR_FILE="dist/wqp-$WQP_VERSION.tar.gz" >> $BASH_ENV

    - name: Publish on GemFury
      env: 
        FURY_PUSH_TOKEN: ${{ secrets.FURY_PUSH_TOKEN}}
        FURY_USER_NAME: ${{ secrets.FURY_PUSH_TOKEN}}
      run: |
        echo Pushing file $TAR_FILE to gemfury...
        curl -F "package=@dist/wqp-$WQP_VERSION.tar.gz" "https://$FURY_PUSH_TOKEN@push.fury.io/$FURY_USER_NAME/"
