name: Test

on: [push]

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run ci
        run: |
          pip install -r requirements.txt
          pytest -s --rootdir=./ --cache-clear tests
